package constants

const (
	SUCCESS                       = 200
	MISSING_PARAMETER_FAIL        = 2000
	ERROR_FAIL                    = 4000
	PLEASE_LOG_IN_FIRST           = 3000
	USERNAME_OR_PASSWD_ERROR_FAIL = 4001
	USERNAME_ALREADY_EXISTS       = 4002
	TOKEN_INVALID                 = 4003
	TOKEN_BE_OVERDUE              = 4004
	SSH_CONNECTION_FAILED         = 4005
	TWO_PASSWORD_INCONSISTENCY    = 4006
	PASSWORD_CANNOT_BE_EMPTY      = 4007
	MACHINE_ID                    = 4008
	MACHINE_PASSWD_NOT_NILL       = 4009
	SERVER_CONFIG_ERR             = 4010
	MACHINE_PASSWD_DECODE_FAIL    = 4011
)
